import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;

public class NumberGuessing_Game {
    private JButton guessButton;
    private JTextField outputTextField;
    private JTextField inputGuess;
    private JPanel guessTheNumber;
    private JTextField score;
    public int randomNumber;
    public int noOfGuesses;

    public NumberGuessing_Game() {
        Random rand=new Random();
        randomNumber=rand.nextInt(100);
        guessButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                int inputNumber=Integer.parseInt(inputGuess.getText());
                noOfGuesses++;
                if(inputNumber==randomNumber) {
                    outputTextField.setText("Yes, You Guessed it right!!!");
                    System.out.println("Random number generated by computer : " + randomNumber);
                    System.out.println("Final score : " + noOfGuesses);
                    JOptionPane.showMessageDialog(null, "Congratulations! You guessed the right number.");
                    System.exit(0); // Close the entire application
                }
                else if (randomNumber==inputNumber+1 || randomNumber==inputNumber-1) {
                    outputTextField.setText("Too close...");
                }
                else if (inputNumber<randomNumber) {
                    outputTextField.setText("Too small...");
                }
                else if (inputNumber>randomNumber) {
                    outputTextField.setText("Too big...");
                }
                score.setText(String.valueOf(noOfGuesses));
            }

        });
    }
    public static void main(String[] args) {
        JFrame frame=new JFrame("NumberGuessingGame");
        frame.setContentPane(new NumberGuessing_Game().guessTheNumber);
        frame.setSize(550,350);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);

    }
}
